name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend:
    name: Frontend Workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      ## —— NPM ————————————————————————————————————————————————
      - name: Install Dependencies
        run: |
          npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Webpack Encore
        run: npm run build:prod

  server:
    name: Symfony Build
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 33016:3306
        options: --health-cmd="mysqladmin ping -proot" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:33016/test_db?serverVersion=10.4.4-MariaDB&charset=utf8"
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.3']
    steps:
      # —— Setup Github actions 🐙 —————————————————————————————————————————————
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      ## —— Coding standards ✨ ————————————————————————————————————————————————

      - name: Coding standards checks
        run: |
          composer run php:cs-fix
          composer run php:lint
        if: matrix.php-versions == '8.3'

      ## —— Static analysis ✨ —————————————————————————————————————————————————
      - name: Static analysis of PHP code (PHPStan)
        run: |
          composer run php:stan

      ## —— Tests ✅ ———————————————————————————————————————————————————————————
      - name: PHPUnit Tests
        run: composer run php:test
